todo_manager/app/urls.py
from django.contrib import admin
from django.urls import include, path

import todo.views.general

urlpatterns = [
    path('addemine/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', todo.views.general.index, name='index')
]

todo_manager/todo/urls.py
from django.urls import path

import todo.views.api as api_views
import todo.views.timetables as timetables_views
import todo.views.todo as todo_views
import todo.views.general as general_views

app_name = 'todo'

urlpatterns = [
    path('', general_views.index, name='index'),
    path('firefox_config/', general_views.firefox_config, name='firefox_config'),

    path('abstract_timetables/', timetables_views.abstract_timetables_list, name='abstract_timetables.list'),

    path('api/ics/<str:token>', api_views.api_ics, name='api.ics'),
    path('api/dialogue_states_for_list/', api_views.api_dialogue_states_for_list, name='api.dialogue_states_for_list'),
    path('api/dialogue_states_push/', api_views.api_dialogue_states_push, name='api.dialogue_states_push'),
    path('api/dialogue_states_color_map/', api_views.api_dialogue_states_color_map, name='api.dialogue_states_color_map'),

    path('todo/<str:list_context>/', todo_views.list, name='todo.list'),
    path('todo/<str:list_context>/all', todo_views.list, {'all': True}, name='todo.all'),
    path('todo/<str:list_context>/new', todo_views.new_or_edit, name='todo.new'),
    path('todo/<str:list_context>/show/<int:pk>', todo_views.show, name='todo.show'),
    path('todo/<str:list_context>/edit/<int:pk>', todo_views.new_or_edit, name='todo.edit'),
    path('todo/<str:list_context>/delete/<int:pk>', todo_views.delete, name='todo.delete'),
    path('todo/<str:list_context>/toggle_cancel/<int:pk>', todo_views.toggle_cancel, name='todo.toggle_cancel'),
    path('todo/<str:list_context>/finish/<int:pk>', todo_views.finish, name='todo.finish'),
]

todo_manager/app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, height=device-height, user-scalable=no, user-scalable=0;"/>
        <title>TDM - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/custom/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom/custom-spectre.css' %}">
        <link rel="stylesheet" href="{% static 'css/lib/spectre-exp.css' %}">
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    </head>
    <body class="plex">
        <header class="navbar bg-dark p-2 p-sticky p-top-0 z-1000">
            <section class="navbar-section m-2">
                <a class="text-light mr-2 h4" href="/">To-Do Manager</a>
                <span class="h4 mr-2">
                    / <a href="" class="text-light">{% block bar_title %}{% endblock %} {% block bar_addendum %}{% endblock %}</a>
                </span>
            </section>

            <section class="navbar-section m-2">
                <div class="mx-2">
                    <a class="text-light" href="{% url 'todo:todo.list' list_context='any' %}">Todos</a>&nbsp;&nbsp;
                    {% for list in todo_lists %}
                        <a class="text-light" href="{% url 'todo:todo.list' list_context=list.url_key %}">{{list.short_name}}</a>&nbsp;&nbsp;/&nbsp;
                    {% endfor %}
                    <span class=""><a class="text-light" href="#">More...</a></span>
                    {# <a class="text-light btn btn-link" href="" %}>le jeu</a> #}
                </div>
                <div class="divider-vert"></div>
                <div class="mx-2">
                    <a class="text-light" href="{% url 'todo:abstract_timetables.list' %}">Timetables</a>
                </div>
                <div class="divider-vert"></div>
                <div class="mx-2">
                    <a class="text-light" href="{% url 'todo:firefox_config' %}">Config</a>
                </div>
                <div class="divider-vert"></div>
                <div class="mx-2">
                    {{user}}&nbsp;/&nbsp;<a class="text-light" href="{% url 'logout' %}">Logout</a>
                </div>
            </section>
        </header>

        <div class="container mt-2">
            {% for message in messages %}
                <div class="toast toast-{{ message.tags | default:'primary' }} mb-2">
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                </div>
            {% endfor %}
            {% block body %}{% endblock %}
        </div>
    </body>
    {% block js %}{% endblock %}
</html>

todo_manager/app/templates/base_public.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, height=device-height, user-scalable=no, user-scalable=0;"/>
        <title>TDM - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/custom/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom/custom-spectre.css' %}">
        <link rel="stylesheet" href="{% static 'css/lib/spectre-exp.css' %}">
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    </head>
    <body class="plex">
        <header class="navbar bg-dark p-2 p-sticky p-top-0 z-1000">
            <section class="navbar-section m-2">
                <a class="text-light mr-2 h4" href="{% url 'todo:index' %}">To-Do Manager</a><span class="h4 mr-2">/ <a href="" class="text-light">{% block bar_title %}{% endblock %} {% block bar_addendum %}{% endblock %}</a></span>
            </section>
        </header>

        <div class="container mt-2">
            {% for message in messages %}
                <div class="toast toast-{{ message.tags | default:'primary' }} mb-2">
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                </div>
            {% endfor %}
            {% block body %}{% endblock %}
        </div>
    </body>
    {% block js %}{% endblock %}
</html>