todo_manager/app/urls.py
from django.contrib import admin
from django.urls import include, path

import todo.views.general

urlpatterns = [
    path('addemine/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', todo.views.general.index, name='index')
]

todo_manager/todo/urls.py
from django.urls import path

import todo.views.api as api_views
import todo.views.timetables as timetables_views
import todo.views.todo as todo_views
import todo.views.general as general_views

app_name = 'todo'

urlpatterns = [
    path('', general_views.index, name='index'),
    path('firefox_config/', general_views.firefox_config, name='firefox_config'),

    path('abstract_timetables/', timetables_views.abstract_timetables_list, name='abstract_timetables.list'),

    path('api/ics/<str:token>', api_views.api_ics, name='api.ics'),
    path('api/dialogue_states_for_list/', api_views.api_dialogue_states_for_list, name='api.dialogue_states_for_list'),
    path('api/dialogue_states_push/', api_views.api_dialogue_states_push, name='api.dialogue_states_push'),
    path('api/dialogue_states_color_map/', api_views.api_dialogue_states_color_map, name='api.dialogue_states_color_map'),

    path('todo/<str:list_context>/', todo_views.list, name='todo.list'),
    path('todo/<str:list_context>/all', todo_views.list, {'all': True}, name='todo.all'),
    path('todo/<str:list_context>/new', todo_views.new_or_edit, name='todo.new'),
    path('todo/<str:list_context>/show/<int:pk>', todo_views.show, name='todo.show'),
    path('todo/<str:list_context>/edit/<int:pk>', todo_views.new_or_edit, name='todo.edit'),
    path('todo/<str:list_context>/delete/<int:pk>', todo_views.delete, name='todo.delete'),
    path('todo/<str:list_context>/toggle_cancel/<int:pk>', todo_views.toggle_cancel, name='todo.toggle_cancel'),
    path('todo/<str:list_context>/finish/<int:pk>', todo_views.finish, name='todo.finish'),
]

todo_manager/todo/models.py
from django.db import models
from django_better_choices import choices
from django.conf import settings
from django.core.exceptions import ValidationError
from django.shortcuts import reverse
# from django.contrib.auth.hashers import check_password, make_password

from datetime import timedelta, datetime
import ics


class TodoList(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=127, null=True)
    order = models.IntegerField(null=True)
    url_key = models.CharField(max_length=127, unique=True)
    hex_color = models.CharField(max_length=6)

    def __str__(self):
        return f'List {self.name}'


class Todo(models.Model):
    class Importantness(models.TextChoices):
        NOT_IMPORTANT = ('0_not', 'Not important at all')
        NOT_IMPORTANT_BUT_I_SHOULD_DO_IT = ('1_i_should_do_it', 'Not -important- but i "should" do it for myself')
        IMPORTANT = ('2_important', 'Important')

    class Urgency(models.TextChoices):
        NOT_URGENT = ('0_not', 'Not urgent at all')
        GETTING_URGENT = ('1_getting_urgent', 'Getting urgent')
        URGENT = ('2_urgent', 'Urgent')

    class DialogueState(choices.BetterChoices):
        NOT_STARTED = ('0_not', 'I must start the dialogue', 'error')
        WAITING = ('1_waiting', 'It\'s on/I am waiting for responses', 'success')
        NEED_CONTINUE = ('2_need_continue', 'I must continue the dialogue/ask new questions', 'error')
        NEED_DO = ('3_need_do', 'I must do the task', 'error')
        FINISHED = ('99_finished', 'The dialogue is finished', 'success')

    title = models.CharField(max_length=256)
    creation_date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('TodoTag', related_name='todos', blank=True)
    related_todos = models.ManyToManyField('self', blank=True)
    done_date = models.DateTimeField(null=True, blank=True, help_text='Default is now')
    cancelled = models.BooleanField(default=False)
    urgency = models.CharField(max_length=32, choices=Urgency.choices, default=Urgency.NOT_URGENT)
    importantness = models.CharField(max_length=32, choices=Importantness.choices, default=Importantness.NOT_IMPORTANT)
    could_do = models.BooleanField(default=False)
    list = models.ForeignKey(TodoList, on_delete=models.CASCADE, null=True, blank=True)
    dialogue_state = models.CharField(max_length=32, choices=DialogueState.choices, null=True, blank=True, help_text='Leave blank if needed')
    # dialogue_person = models.ForeignKey()
    todo_by_date = models.DateTimeField(null=True, blank=True, help_text='Leave blank if needed')

    def __str__(self):
        return f'{self.title}'

    def get_dialogue_state_color(self):
        return self.DialogueState.additional_attributes_by_db_name[self.dialogue_state][0]

    @property
    def searchtext(self):
        return f'{self.title} {" ".join([detail.detail_text for detail in self.details.all()])}'

    @property
    def is_urgent(self):
        return self.urgency != self.Urgency.NOT_URGENT

    @property
    def is_important(self):
        return self.importantness != self.Importantness.NOT_IMPORTANT

    @property
    def is_dialogue(self):
        return self.dialogue_state is not None


class TodoDetail(models.Model):
    detail_text = models.CharField(max_length=256)
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE, related_name='details')


class TodoTag(models.Model):
    name = models.CharField(max_length=32)


class TodoBumpEvent(models.Model):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE, related_name='bumps')
    date = models.DateTimeField(auto_now_add=True)


class TelegramSubscription(models.Model):
    chat_id = models.BigIntegerField(unique=True)  # Telegram doc says this is <52 bit
    who = models.CharField(max_length=64)


class TelegramUpdateRecord(models.Model):
    update_id = models.BigIntegerField(unique=True)

    @classmethod
    def last_update_id(cls):
        singleton = cls.objects.first()
        if singleton:
            return singleton.update_id
        else:
            return -1

    @classmethod
    def set_last_update_id(cls, update_id):
        singleton = cls.objects.first()
        if singleton:
            singleton.update_id = update_id
        else:
            singleton = cls.objects.create(update_id=update_id)
        singleton.save()


class AbstractTimetable(models.Model):
    """A set of time slots defined over an abstract week."""
    name = models.CharField(max_length=128)


class AbstractTimeSlot(models.Model):
    class Weekday(models.IntegerChoices):
        MONDAY = 0
        TUESDAY = 1
        WEDNESDAY = 2
        THURSDAY = 3
        FRIDAY = 4
        SATURDAY = 5
        SUNDAY = 6

    template = models.ForeignKey(AbstractTimetable, on_delete=models.CASCADE, related_name='time_slots')
    begin_time = models.TimeField()
    end_time = models.TimeField()
    weekday = models.IntegerField(choices=Weekday.choices)

    def clean(self):
        cleaned_data = super().clean()
        begin_time = cleaned_data['begin_time']
        end_time = cleaned_data['end_time']

        if end_time <= begin_time:
            raise ValidationError('End time must be after begin time')


class ConcreteTimeSlot(models.Model):
    monday_of_that_week = models.DateField()
    abstract_time_slot = models.ForeignKey(AbstractTimeSlot, on_delete=models.CASCADE)
    attributed_todo = models.ForeignKey(Todo, on_delete=models.CASCADE)

    @property
    def concrete_begin_time(self):
        monday_of_that_week_midnight = datetime(
            self.monday_of_that_week.year,
            self.monday_of_that_week.month,
            self.monday_of_that_week.day
        )

        return monday_of_that_week_midnight + timedelta(
            days=self.abstract_time_slot.weekday,
            hours=self.abstract_time_slot.begin_time.hour,
            minutes=self.abstract_time_slot.begin_time.minute,
        )

    @property
    def concrete_end_time(self):
        monday_of_that_week_midnight = datetime(
            self.monday_of_that_week.year,
            self.monday_of_that_week.month,
            self.monday_of_that_week.day
        )

        return monday_of_that_week_midnight + timedelta(
            days=self.abstract_time_slot.weekday,
            hours=self.abstract_time_slot.end_time.hour,
            minutes=self.abstract_time_slot.end_time.minute,
        )

    @property
    def ics_event(self):
        return ics.event.Event(
            name=self.attributed_todo.name,
            begin=self.concrete_begin_time,
            end=self.concrete_end_time,
            location='{}{}'.format(settings.ICS_DJANGO_HOST, reverse('todo:show', args=['any', self.attributed_todo.pk]))
        )


# class TodoUserAddons(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     ics_secret_token = models.CharField(max_length=128)
#
#     def set_ics_secret_token(self, new_token):
#         self.ics_secret_token = make_password(new_token)
#
#     def check_ics_secret_token(self, token):
#         return check_password(token, self.ics_secret_token)

todo_manager/todo/forms.py
from django import forms
from django.utils.timezone import now

from todo.models import Todo, TodoDetail


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        exclude = ['done_date', 'cancelled']
        widgets = {
            'todo_by_date': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs["autofocus"] = True


class TodoFinishForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['done_date']
        widgets = {
            'done_date': forms.DateInput(attrs={'type': 'date'})
        }

    def clean_done_date(self):
        data = self.cleaned_data['done_date'] or now()
        self.cleaned_data['done_date'] = data
        return data


TodoDetailFormSet = forms.inlineformset_factory(Todo, TodoDetail, fields=['detail_text'])

todo_manager/todo/views/api.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import JsonResponse, HttpResponse, Http404
from django.conf import settings

import json
import ics as ics_lib

from todo.models import Todo, ConcreteTimeSlot
from todo.views.utils import todo_list_qs


@login_required
def api_dialogue_states_for_list(request):
    qs = todo_list_qs(request.GET['list'], request.GET['all'])
    ret = {todo.pk: todo.dialogue_state for todo in qs if todo.is_dialogue}
    return JsonResponse(ret)


@login_required
def api_dialogue_states_push(request):
    data = json.loads(request.body)
    obj = get_object_or_404(Todo, pk=data['pk'])

    if request.method == 'POST':
        if obj.is_dialogue:
            obj.dialogue_state = data['dialogue_state']
            obj.save()
            return JsonResponse({'saved': True})

    return JsonResponse({'saved': False})


@login_required
def api_dialogue_states_color_map(request):
    dummy = Todo()
    x = dummy.DialogueState.additional_attributes_by_db_name
    ret = {key: value[0] for key, value in x.items()}

    return JsonResponse(ret)


def api_ics(request, token):
    if token == settings.ICS_TOKEN:
        cal = ics_lib.icalendar.Calendar()
        cal.creator = '-//maltherd//NONSGML tdm_ics//EN'
        for cts in ConcreteTimeSlot.objects.all():
            cal.add(cts.ics_event)

        # HttpResponse can consume iterators, of which cal is one
        resp = HttpResponse(cal, headers={
            'Content-Type': 'text/calendar'
        })

        return resp

    raise Http404

todo_manager/todo/views/general.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse


@login_required
def index(request):
    return redirect(reverse('todo:todo.list', kwargs={'list_context': 'any'}))


@login_required
def firefox_config(request):
    return render(request, 'todo/general/firefox_config.html')

todo_manager/todo/views/timetables.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse, get_object_or_404


from todo.models import ConcreteTimeSlot


@login_required
def abstract_timetables_list(request):
    pass

todo_manager/todo/views/todo.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse, get_object_or_404

from functools import wraps

from todo.models import TodoList, Todo
from todo.forms import TodoForm, TodoFinishForm, TodoDetailFormSet
from todo.views.utils import todo_list_qs


def list_contextualized(f):
    @wraps(f)
    def wrapped(*args, **kwargs):
        if 'list_context' in kwargs:

            class FakeList:
                url_key = 'any'

                def __bool__(self):
                    return False

            list = FakeList() if kwargs['list_context'] == 'any' else get_object_or_404(TodoList, url_key=kwargs['list_context'])
            del kwargs['list_context']
            kwargs['list'] = list

        return f(*args, **kwargs)

    return wrapped


@login_required
@list_contextualized
def list(request, list, all=False):
    qs = todo_list_qs(list, all)
    return render(request, 'todo/todo/listnew.html', {'qs': qs, 'list': list, 'all': all})


@login_required
@list_contextualized
def new_or_edit(request, list, pk=None):
    """Credits to https://stackoverflow.com/questions/1113047/creating-a-model-and-related-models-with-inline-formsets"""

    obj = get_object_or_404(Todo, pk=pk) if pk else None

    if request.method == 'POST':
        form = TodoForm(request.POST, instance=obj)
        if form.is_valid():
            todo = form.save(commit=False)
            details_formset = TodoDetailFormSet(request.POST, instance=obj or todo)
            if details_formset.is_valid():
                form.save()
                details_formset.save()

                messages.success(request, 'Todo saved!')
                return redirect(reverse('todo:todo.show', kwargs={'pk': pk, 'list_context': list.url_key}) if pk else reverse('todo:todo.list', kwargs={'list_context': list.url_key}))

    else:
        form = TodoForm(instance=obj, initial={'list': list} if not obj else {})  # do not override pre-existing info with initial; only suggest new data.
        details_formset = TodoDetailFormSet(instance=obj or Todo())

    return render(request, 'todo/todo/new_or_edit.html', {'obj': obj, 'list': list, 'form': form, 'details_formset': details_formset})


@login_required
@list_contextualized
def show(request, list, pk):
    obj = get_object_or_404(Todo, pk=pk)
    return render(request, 'todo/todo/show.html', {'obj': obj, 'list': list})


@login_required
@list_contextualized
def delete(request, list, pk):
    obj = get_object_or_404(Todo, pk=pk) if pk else None

    if request.method == 'POST':
        obj.delete()
        messages.success(request, 'Todo deleted!')
        return redirect(reverse('todo:todo.list'), kwargs={'list_context': list.url_key})

    return render(request, 'todo/todo/delete.html', {'obj': obj, 'list': list})


@login_required
@list_contextualized
def toggle_cancel(request, list, pk):
    obj = get_object_or_404(Todo, pk=pk) if pk else None

    if request.method == 'POST':
        obj.cancelled = not obj.cancelled
        obj.save()

        messages.success(request, 'Todo cancelled!' if obj.cancelled else 'Todo un-cancelled!')
        return redirect(reverse('todo:todo.show', kwargs={'pk': pk, 'list_context': list.url_key}))

    return render(request, 'todo/todo/toggle_cancel.html', {'obj': obj, 'list': list})


@login_required
@list_contextualized
def finish(request, list, pk):
    obj = get_object_or_404(Todo, pk=pk) if pk else None

    if request.method == 'POST':
        form = TodoFinishForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()

            messages.success(request, 'Todo finished!')
            return redirect(reverse('todo:todo.list', kwargs={'list_context': list.url_key}))

    else:
        form = TodoFinishForm(instance=obj)

    return render(request, 'todo/todo/finish.html', {'obj': obj, 'form': form, 'list': list})

todo_manager/todo/views/utils.py
from django.utils.timezone import now

from datetime import timedelta

from todo.models import Todo


def todo_list_qs(list, all):
    qs = Todo.objects.order_by('-dialogue_state', '-urgency', '-importantness', 'creation_date', 'could_do').filter(done_date__isnull=True).filter(cancelled=False)

    if not all:
        qs = qs.filter(creation_date__gt=now()-timedelta(days=60))

    if list:
        qs = qs.filter(list=list)

    return qs

todo_manager/todo/templates/todo/todo/delete.html
{% extends 'base.html' %}
{% load spectre_css %}

{% block title %}Todos - Delete{% endblock %}
{% block bar_title %}Todos / Delete{% endblock %}

{% block body %}
<div class="divider"></div>
<div class="columns col-gapless">
    <div class="column col-12 px-1">
        <div class="card card-shadow mb-2">
            <div class="card-header">
                <span class="h5 card-title">{{obj}}</span>
            </div>
            <div class="card-body">
                Do you really want to delete this todo?
            </div>
        </div>
        <div class="card card-shadow mb-2">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <a href="{% url 'todo:todo.show' pk=obj.pk list_context=list.url_key %}" class="btn btn-link">Back</a>
                    <input type="submit" class="btn btn-link" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todo_manager/todo/templates/todo/todo/finish.html
{% extends 'base.html' %}
{% load spectre_css %}

{% block title %}Todos - Finish{% endblock %}
{% block bar_title %}Todos / Finish{% endblock %}

{% block body %}
<div class="divider"></div>
<form action="" method="post">
    <div class="columns col-gapless">
        <div class="column col-12 px-1">
            <div class="card card-shadow mb-2">
                <div class="card-header">
                    <span class="h5 card-title">{{obj}}</span>
                </div>
                <div class="card-body">
                    {% render_form form %}
                </div>
            </div>
            <div class="card card-shadow mb-2">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <a href="{% url 'todo:todo.show' pk=obj.pk list_context=list.url_key %}" class="btn btn-link">Back</a>
                        <input type="submit" class="btn btn-link" value="Finish">
                    </form>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

todo_manager/todo/templates/todo/todo/new_or_edit.html
{% extends 'base.html' %}
{% load spectre_css %}

{% block title %}Todos - Edit/New{% endblock %}
{% block bar_title %}Todos / {% if obj %}Edit{% else %}New{% endif %}{% endblock %}
{% block bar_addendum %}{% if list %}<span style="color: #{{list.hex_color}};">{{list.short_name}}</span>{% endif %}{% endblock %}

{% block body %}
<div class="divider"></div>
<form action="" method="post">
    <div class="columns col-gapless">
        {% csrf_token %}
        <div class="column col-12 px-1">
            <div class="card card-shadow mb-2">
                <div class="card-header">
                    <span class="h5 card-title">{{obj | default:'New todo'}}</span>
                </div>
                <div class="card-body">
                    {% render_form_header form %}
                    {% for field in form.visible_fields %}
                        {% render_form_field field switch=True %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {{details_formset.management_form}}
        {% for f in details_formset %}
            <div class="card-column-flex-grow column col-xl-5 col-2 px-1">
                <div class="card card-shadow mb-2">
                    <div class="card-body">
                        {% render_form f %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="column col-12 px-1">
            <div class="card card-shadow mb-2">
                <div class="card-body">
                    <a href="{% if obj %}{% url 'todo:todo.show' pk=obj.pk list_context=list.url_key %}{% else %}{% url 'todo:todo.list' list_context=list.url_key %}{% endif %}" class="btn btn-link">Back</a>
                    <input type="submit" class="btn btn-link" value="Save">
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

todo_manager/todo/templates/todo/todo/show.html
{% extends 'base.html' %}
{% load spectre_css %}

{% block title %}Todos - Show{% endblock %}
{% block bar_title %}Todos / Show{% endblock %}
{% block bar_addendum %}{% if list %}<span style="color: #{{list.hex_color}};">{{list.short_name}}</span>{% endif %}{% endblock %}

{% block body %}
<div class="divider"></div>
<div class="columns col-gapless">
    <div class="column col-12 px-1">
        <div class="card card-shadow mb-2">
            <div class="card-header">
                <span class="h5 card-title">{{obj}}</span>
            </div>
            <div class="card-body">
                <dl>
                    <dt>List?</dt>
                    <dd>
                        {% if obj.list %}
                            Yes, in {{obj.list.name}} <i class="icon icon-bookmark" style="color: #{{obj.list.hex_color}};"></i>.
                        {% else %}
                            No.
                        {% endif %}
                    </dd>
                    <dt>Done ?</dt>
                    <dd>
                        {% if obj.done_date %}
                            Yes, on {{obj.done_date | date}}
                        {% elif obj.cancelled %}
                            No, and the todo is cancelled.
                        {% else %}
                            Not yet.
                        {% endif %}
                    </dd>
                    <dt>Tags</dt>
                    <dd>
                        {% for item in obj.tags.all %}
                            <a class="label">{{item.name}}</a>
                        {% endfor %}
                    </dd>
                    <dt>Important?</dt>
                    <dd>
                        {{obj.get_importantness_display}}
                    </dd>
                    <dt>Urgent?</dt>
                    <dd>
                        {{obj.get_urgency_display}}
                    </dd>
                    <dt>Dates</dt>
                    <dd>
                        Created {{obj.creation_date}} - {{obj.creation_date | timesince}} ago<br/>
                        {% if obj.todo_by_date %}
                            To do by {{obj.todo_by_date}} - in {{obj.todo_by_date | timeuntil}}
                        {% else %}
                            No deadline :)
                        {% endif %}
                    </dd>
                    <dt>Related</dt>
                    <dd>
                        <ul>
                            {% for item in obj.related_todos.all %}
                                <li><a href="{% url 'todo:todo.show' list_context=list.url_key pk=item.pk %}">{{item}}</a></li>
                            {% endfor %}
                        </ul>
                    </dd>
                    <dt>Details</dt>
                    <dd>
                        <ul>
                            {% for item in obj.details.all %}
                                <li>{{item.detail_text | urlize}}</li>
                            {% endfor %}
                        </ul>
                    </dd>
                </dl
            </div>
        </div>
    </div>
    <div class="column col-12 px-0">
        <div class="card card-shadow mb-2">
            <div class="card-body">
                <a href="{% url 'todo:todo.list' list_context=list.url_key %}" class="btn btn-link">Back</a>
                <a href="{% url 'todo:todo.edit' pk=obj.pk list_context=list.url_key %}" class="btn btn-link">Edit</a>
                {% if not obj.done_date %}
                    <a href="{% url 'todo:todo.finish' pk=obj.pk list_context=list.url_key %}" class="btn btn-link">Finish</a>
                {% endif %}
                <button class="btn btn-link" type="button">Bump</button>
                <a href="{% url 'todo:todo.toggle_cancel' pk=obj.pk list_context=list.url_key %}" class="btn btn-link">{% if obj.cancelled %}Un-{% endif %}Cancel</a>
                <a href="{% url 'todo:todo.delete' pk=obj.pk list_context=list.url_key %}" class="btn btn-link">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todo_manager/todo/templates/todo/todo/toggle_cancel.html
{% extends 'base.html' %}
{% load spectre_css %}

{% block title %}Todos - Toggle cancel{% endblock %}
{% block bar_title %}Todos / Toggle cancel{% endblock %}

{% block body %}
<div class="divider"></div>
<div class="columns col-gapless">
    <div class="column col-12 px-1">
        <div class="card card-shadow mb-2">
            <div class="card-header">
                <span class="h5 card-title">{{obj}}</span>
            </div>
            <div class="card-body">
                Do you really want to {% if obj.cancelled %}un-{% endif %}cancel this todo?
            </div>
        </div>
        <div class="card card-shadow mb-2">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <a href="{% url 'todo:todo.show' pk=obj.pk list_context=list.url_key %}" class="btn btn-link">Back</a>
                    <input type="submit" class="btn btn-link" value="{% if obj.cancelled %}Un-{% endif %}Cancel">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}